
# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'



[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo='qpkorr/vim-renamer'


[[plugins]]
repo='Shougo/denite.nvim'

#[[plugins]]
#repo='Shougo/deol.nvim'

#[[plugins]]
#repo='Shougo/neomru.nvim'

#[[plugins]]
#repo='Shougo/neoyank.nvim'


[[plugins]]
repo='Shougo/neomru.vim'

[[plugins]]
repo='Shougo/neoyank.vim'

