
# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'



[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo='qpkorr/vim-renamer'


[[plugins]]
repo='Shougo/denite.nvim'

#[[plugins]]
#repo='Shougo/neomru.nvim'

#[[plugins]]
#repo='Shougo/neoyank.nvim'


[[plugins]]
repo='Shougo/neomru.vim'

[[plugins]]
repo='Shougo/neoyank.vim'

[[plugins]]
repo='vim-airline/vim-airline'

[[plugins]]
repo='vim-airline/vim-airline-themes'

[[plugins]]
repo='tpope/vim-surround'

[[plugins]]
repo='Shougo/deoplete.nvim'

[[plugins]]
repo='Shougo/neco-vim'

[[plugins]]
repo='Shougo/neco-syntax'


